### ISSUE TITLE
Arduino IDE 1.0 requirement

### ISSUE THREAD

**Issue by treaves** [queezythegreat/arduino-cmake#13]
As much as I'd like to move to this too, there are a lot of extensions out there that can not.  the only thing that makes this a requirement for this project is your use of ARDUINO_VARIANTS_PATH. Surely that could be wrapped in a check for 1.0?

**Comment by queezythegreat** [comment]
I could add backward compatibility. The only issue that I have  right now is with the version numbers.

When a initially wrote arduino-cmake I expected that the versions will be formatted as 00XX and that isn't the case anymore, causing problems. I could normalize the old versions from 00XX to 0.XX making version dependent check much easier...

I'll try to add backward compatibility when I have some free time.

**Comment by treaves** [comment]
I think the idea of going from 00XX to 0.XX would work well.

**Comment by queezythegreat** [comment]
Closing, ticket #18 will be the official ticket for this feature request.
