### ISSUE TITLE
Add setting to specify ARDUINO_SDK_PATH

### ISSUE THREAD

**Issue by treaves** [queezythegreat/arduino-cmake#15]
It'd be nice to be able to set this in the CMakeLists.txt file, as I'm forced to have more than one version installed.  I think this would only take putting a conditional around the find_path directive.

**Comment by queezythegreat** [comment]
You can actually set it during the build system generation using  the `-D` option:

```
cmake -D ARDUINO_SDK_PATH=/path/to/arduino_sdk ../path/to/sources
```

If `ARDUINO_SDK_PATH` is set, `find_path` does nothing.

**Comment by treaves** [comment]
O.K.  thanks.
