### ISSUE TITLE
CMAKE_C_FLAGS and CMAKE_CXX_FLAGS empty if build type empty

### ISSUE THREAD

**Issue by dlobato** [queezythegreat/arduino-cmake#20]
If no build type is selected CMAKE_C_FLAGS and CMAKE_CXX_FLAGS are set empty, regardless the value set on the toolchain file. This causes warnings on compile time like: 

```
delay.h:95:3: warning: #warning "Compiler optimizations disabled; functions from <util/delay.h> won't work as designed"
```

**Comment by dlobato** [comment]
It seems to be related with the integration with ros. I'm trying to update the cmake support to 1.0 in [rosserial](https://kforge.ros.org/rosserial/hg/file/10cb30606b34/rosserial_arduino/cmake_scripts). It seems they have added some lines at the end of the toolchain to force some values.

**Comment by queezythegreat** [comment]
rosserial has done extensive modifications of Arduino CMake, I don't have a clue what the problem may be. Closing as rosserial is not Arduino CMake.
