### ISSUE TITLE
undefined reference to 'loop' revisited

### ISSUE THREAD

**Issue by mafox** [queezythegreat/arduino-cmake#24]
I know that you closed a previous entry concerning this topic  in January 2012 but please bear with me. I have a new UNO R3 board and am on a windows 7 machine. I have attempted to load the example library TEST, which produces the above error. Even though I follow your conclusion that the problem is in the linkage of the libraries, I really need explicit steps in how to accomplish this.
Thanks.

**Comment by queezythegreat** [comment]
Closing, due to inactivity....
