### ISSUE TITLE
Core includes main.cxx and build fails

### ISSUE THREAD

**Issue by jgoppert** [queezythegreat/arduino-cmake#3]
In the latest arduino 22 version the core directory contains both a main.cpp and main.cxx, the main.cxx doesn't include WProgram.h and the core build fails because of this.

**Comment by queezythegreat** [comment]
What OS are you using? I have heard that Ubuntu ships with the Arduino SDK that has this problem.

**Comment by jgoppert** [comment]
I'm running debian wheezy. So same sdk as ubuntu. I have committed a fix on my fork:

```
function(setup_arduino_core VAR_NAME BOARD_ID)
    set(CORE_LIB_NAME ${BOARD_ID}_CORE)
    set(BOARD_CORE ${${BOARD_ID}.build.core})
    if(BOARD_CORE AND NOT TARGET ${CORE_LIB_NAME})
        set(BOARD_CORE_PATH ${ARDUINO_CORES_PATH}/${BOARD_CORE})
        find_sources(CORE_SRCS ${BOARD_CORE_PATH})
        list(REMOVE_ITEM CORE_SRCS "${BOARD_CORE_PATH}/main.cxx")
        add_library(${CORE_LIB_NAME} ${CORE_SRCS})
        set(${VAR_NAME} ${CORE_LIB_NAME} PARENT_SCOPE)
    endif()
endfunction()
```

 but am now running into this error building ardupilot-mega:

```
Linking CXX executable apo.elf
/usr/bin/cmake -E cmake_link_script CMakeFiles/apo.dir/link.txt --verbose=1
/usr/bin/avr-g++   -g -Os       -ffunction-sections -fdata-sections -fno-exceptions  -Wl,--gc-sections -lc -lm    -mmcu=atmega1280 CMakeFiles/apo.dir/apo.cpp.obj  -o apo.elf  -lc -lm libs/APO/libAPO.a libs/FastSerial/libFastSerial.a libs/AP_Common/libAP_Common.a libs/GCS_MAVLink/libGCS_MAVLink.a libs/AP_GPS/libAP_GPS.a libs/APM_RC/libAPM_RC.a libs/AP_DCM/libAP_DCM.a libs/AP_ADC/libAP_ADC.a libs/AP_Compass/libAP_Compass.a libs/AP_IMU/libAP_IMU.a libs/AP_RangeFinder/libAP_RangeFinder.a libs/APM_BMP085/libAPM_BMP085.a libs/ModeFilter/libModeFilter.a libs/APM_BMP085/libmega_Wire.a libs/AP_ADC/libmega_CORE.a 
libs/AP_ADC/libmega_CORE.a(main.cpp.obj): In function `main':
/usr/share/arduino/hardware/arduino/cores/arduino/main.cpp:7: undefined reference to `setup'
/usr/share/arduino/hardware/arduino/cores/arduino/main.cpp:10: undefined reference to `loop'
```

**Comment by queezythegreat** [comment]
Do you have setup() and loop() functions defined somewhere?

**Comment by jgoppert** [comment]
Yes, it is in the main file apo.pde. It seems that the library (AP_ADC) is trying to link against main.cpp?

**Comment by jgoppert** [comment]
Here is my CMakeLists.txt if you want to check it out. https://code.google.com/p/ardupilot-mega/source/browse/apo/CMakeLists.txt

**Comment by queezythegreat** [comment]
The reason you are getting these errors is because PDE processing is disabled (not implemented). So all your PDE files are not getting compiled, hence the setup() and loop() are missing. 

You need to convert your PDE files to C/C++, meaning change the extension to .c or .cpp and add:
#include "WProgram.h"
to the top of the files.

The ${TARGET_NAME}_SKETECHES does nothing currently.

**Comment by jgoppert** [comment]
Thanks for the help! I had to add a recurse option to find_sources since arduino typically doesn't recurse for user added libraries. You should be able to pull it from my fork. The  work you did with the libraries was very helpful. I reduced all of our CMakeLists.txt files down to one.
