### ISSUE TITLE
Preprocessor fails for complex sketches/ ArduPlane/ ArduQuad

### ISSUE THREAD

**Issue by jgoppert** [queezythegreat/arduino-cmake#33]
I'm currently working on this. I hacked together an arduino command line interface that does all the sketch processing.

https://github.com/arktools/arduino-cmdline

It is still a little bit buggy for finding the preferences file etc, but I should get that worked  out soon. I then think we can just embed the arduino-cmdline.jar inside arduino-cmake. If the user has arduino installed, it is fair to assume that we can use java. This also is much easier to maintain since it is the exact arduino code running. Once we get this cleaned up, we should also be able to get arduino to push it to master.

**Comment by queezythegreat** [comment]
So does that mean that the current version of Arduino CMake fails with ArduPlane and ArduQuad?

Ideally I would like to minimize all external dependencies (such as Java). But we could always have both versions, the cmake one as a fallback.

**Comment by jgoppert** [comment]
Yes, the regex capabilities of cmake were just not enough for me to cover everything exactly as arduino does. There are edge cases where it will fail. Since the ArduPilot/ ArduQuad code base is so large, they found these edge cases. It does work for ArduRover/ ArduBoat. I think that the dual method is a good idea, we can have it passed as an option. Also, i have some minor fixes for the cmake version on my branch of arduino-cmake.

**Comment by queezythegreat** [comment]
Well with enough time and testing, we can probably match the regexes that are in Arduino IDE. Could you give me some links to the sources that fail. I'll try to get the regexes working with those projects. I've tested the regexs only with Razor IMU library, and some of my personal projects (had to adjust the regex that where from you).

Also the reason why I want to have minimal dependencie is that I plan on getting Arduino CMake integrated into CMake code base, so having external dependencies/jar will make it very hard to get it integrated.

**Comment by jgoppert** [comment]
Here are the links to the latest sources, maybe your regex fixes will help: 
http://ardupilot-mega.googlecode.com/files/ArduPlane-2.33.zip
http://arducopter.googlecode.com/files/ArduCopter-2.5.3.zip

I also have some more minor fixes in my arduino-cmake branch.

**Comment by jgoppert** [comment]
I pulled the sketches into my arudino-cmake fork as test cases, so you can just clone mine to see all the errors. git@github.com:jgoppert/arduino-cmake.git

I also updated the cmake for your new functions etc.

**Comment by queezythegreat** [comment]
This is going to take some time... I've upgraded my system and avr-libc has updated to 1.8.0 and I'm having to fix a lot of deprecated typedef (PROGMEM)... :(

**Comment by jgoppert** [comment]
Think i fixed the rest of the prototype issues with cmake, thanks for all your work! See my branch for the changes to Arduino.cmake

**Comment by jgoppert** [comment]
I fixed it to work with ArduPlane, but it seems that there are a still a lot of issues with the sketches. For instance, ArduCopter is trying to include a file from the ArduPilot sketch and failing when it builds. This is due to the fact that none of the include_directories() are tied to a specific sketch, they are all global. We need to make sure all the functions in Arduino.mk have a more clearly defined input/output I think to solve this issue.
