### ISSUE TITLE
Support additional Hardware definitions.

### ISSUE THREAD

**Issue by zeeMonkeez** [queezythegreat/arduino-cmake#40]
The arduino environment allows for additional boards to be defined under the `hardware` folder within the 'sketchbook'. [Arduino Environment](http://arduino.cc/en/Guide/Environment#sketchbook)
Any chance additional boards/programmers could be supported this way?

**Comment by queezythegreat** [comment]
There isin't a `sketchbook` in Arduino CMake. That functionality does not yet exist in _Arduino CMake_.

I do think that being able to specify additional board/programmers configuration files would be great. I haven't looked at how the Arduino handles additional config files yet, but I'll definately will look into it.

When I have some spare time, I'll try to add in the functionality. Thanks for the great suggestion.

http://arduino.cc/en/Guide/Environment#sketchbook
http://code.google.com/p/arduino/wiki/Platforms

**Comment by queezythegreat** [comment]
Closing this issue, new official feature request created in issue #41.
