### ISSUE TITLE
CMake version

### ISSUE THREAD

**Issue by cipherz** [queezythegreat/arduino-cmake#47]
Hello,

First, great work! Just want to hint that maybe it is the cmake that ships with debian stable that is built funny or simply out of date because it does not work, I tried:
mkdir build
cmake ..
....
System is unknown to cmake, create:
Platform/Arduino to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
...

-- Detecting CXX compiler ABI info - done
CMake Error at example/CMakeLists.txt:12 (generate_arduino_example):
  Unknown CMake command "generate_arduino_example".

Not sure if I am doing something incorrectly, but if I install cmake 2.8.8 (debian stable ships with 2.8.2) then it works perfectly.

Also, at least for me I could not use make upload I had to use make blink-upload :)

Thanks!

**Comment by queezythegreat** [comment]
Arduino CMake requires CMake version 2.8.5 and  higher.

**Comment by cipherz** [comment]
Sorry missed that piece of information on the website. Perhaps considering using this statement: cmake_minimum_required(2.8.5) would avoid fools trying to use too old versions of Cmake :) thanks!

**Comment by queezythegreat** [comment]
Actually that command is used internally, it's interesting you did not get an error.

https://github.com/queezythegreat/arduino-cmake/blob/master/cmake/Platform/Arduino.cmake#L157

**Comment by antonpiatek** [comment]
I also see the same thing, so the internal test does not produce an error... was wondering why the code wouldn't work for me :/
