### ISSUE TITLE
Small fix for ARDUINO 1.0.1

### ISSUE THREAD

**Issue by Philomenale** [queezythegreat/arduino-cmake#53]
in order to detect ARDUINO SDK path, 
open the 'ArduinoToolchain.cmake' file and line 41 after  : 

---
# =============================================================================
# Detect Arduino SDK
# =============================================================================

if(NOT ARDUINO_SDK_PATH)
    set(ARDUINO_PATHS)
    foreach(VERSION 22 1)
        list(APPEND ARDUINO_PATHS arduino-00${VERSION})
    endforeach()

---

the 3 following lines need to be added :

---

```
foreach(VERSION 1 2 3)
    list(APPEND ARDUINO_PATHS arduino-1.0.${VERSION})
endforeach()
```

---

**Comment by queezythegreat** [comment]
Thanks for the heads up about the latest version of the Arduino SDK. I'll try to add this as soon as I have some free time. Sorry for responding so late.
