### ISSUE TITLE
Sketches do not compile if the board is set to leonardo

### ISSUE THREAD

**Issue by mdaffin** [queezythegreat/arduino-cmake#54]
If you set the default board to leonardo then skectches (including the example ones) do not compile and produce the follow errors:

```
/usr/share/arduino/hardware/arduino/cores/arduino/USBCore.cpp:78:2: error: 'USB_VID' was not declared in this scope
/usr/share/arduino/hardware/arduino/cores/arduino/USBCore.cpp:78:2: error: 'USB_PID' was not declared in this scope
/usr/share/arduino/hardware/arduino/cores/arduino/USBCore.cpp:81:2: error: 'USB_VID' was not declared in this scope
/usr/share/arduino/hardware/arduino/cores/arduino/USBCore.cpp:81:2: error: 'USB_PID' was not declared in this scope
```

**Comment by queezythegreat** [comment]
Hi, those defines are not being define by Arduino-Cmake, thats why you are getting the error. Arduino-CMake will have to be updated to take into account the new options that appeared in the latest version of the Arduino SDK.

The changes are not extensive, so it should be fixed soon. For now, you can use the following, to fix the problem:

``` cmake
add_definitions(-DUSB_VID=0x2341)
add_definitions(-DUSB_PID=0x8036)
```

Add those two lines to the CMakeLists.txt. These two defines are only used by the Leonardo. Please add this after the `project()` command.

**Comment by cypresi** [comment]
i have the same problem, with an arduino micro, any help?
