### ISSUE TITLE
Arduino v1.0

### ISSUE THREAD

**Issue by chiva** [queezythegreat/arduino-cmake#6]
Are there any plans to support Arduino v1.0?
It has just been released and you can get it from here: http://arduino.cc/en/Main/Software
(at the moment the page has a bug and if you are not logged, the last version you can see is 0023)

Changes to the inner workings are small but significant, changing the pin definitions file, WProgram.h has been renamed to Arduino.h and sketches extension has been changed to .ino.
More info at: http://code.google.com/p/arduino/wiki/Arduino1

I wish I could help to make it compatible but I'm pretty much lost when speaking of Make internals...

**Comment by queezythegreat** [comment]
I will definitely add support for the Arduino IDE 1.0, but when I have time. From what I can see the changes shouldn't impact Arduino CMake too much.

**Comment by treaves** [comment]
So is there some shortcut we can use until you have time?  cmake will not find Arduino IDE 1.0 at all.

**Comment by treaves** [comment]
So far, the regex that detects the version needs to be changed.  I'm using "([0-9]+\.[0-9]+)"

**Comment by queezythegreat** [comment]
Support for Arduino 1.0 has been added (by a contributor), but hasn't yet been merged in. I'm closing this issue for now, I will be merging the changes in a couple of days so stay tuned.

**Comment by treaves** [comment]
Any update on this?

**Comment by queezythegreat** [comment]
Sorry for being quiet for so long, I've been really busy and hadn't had time to do anything with arduino-cmake.

The reason I haven't merged in the changes is because I want to test them out... but I still have Arduino 0022 installed (and haven't had time to upgrade).
