### ISSUE TITLE
Compilation flags not working

### ISSUE THREAD

**Issue by athanase** [queezythegreat/arduino-cmake#63]
Hi there,
I trying to compile project using the library USB_Host_Shied_2.0 and the library generic_storage. I have an error in the library generic_storage which gives me an error that can be deactivated using the flag "-fpermissive". I add those flags in the CMakeLists file but it seems that they are not taken in account during the compilation process.

Here is my [CMakeLists.txt](https://gist.github.com/athanase/5627300#file-cmakelists-txt)

**Comment by mdaffin** [comment]
This is related to #62 which has been merged into the develop branch, I suggest you try the develop branch for now.

**Comment by athanase** [comment]
Thanks for the info, I will try the development branch.
