### ISSUE TITLE
${TARGET}-burn fails on arduino uno, wrong programmer protocol

### ISSUE THREAD

**Issue by antonpiatek** [queezythegreat/arduino-cmake#80]
Attempting to -burn to program my barebones uno (atmega328p) fails with the following error

> [ 90%] Built target uno_CORE
> [100%] Built target cube
> 
> avrdude: AVR device initialized and ready to accept instructions
> 
> Reading | ################################################## | 100% 0.01s
> 
> avrdude: Device signature = 0x000000 (retrying)
> 
> Reading | ################################################## | 100% 0.01s
> 
> avrdude: Device signature = 0x000000 (retrying)
> 
> Reading | ################################################## | 100% 0.01s
> 
> avrdude: Device signature = 0x000000
> avrdude: Yikes!  Invalid device signature.
>          Double check connections and try again, or use -F to override
>          this check.
> 
> avrdude done.  Thank you.

Having read http://forum.arduino.cc/index.php/topic,91580.0.html I changed 
build/CMakeCache.txt:avrisp.protocol:INTERNAL=stk500v1
to
build/CMakeCache.txt:avrisp.protocol:INTERNAL=arduino

Arduino is the UbuntU package at version 1:1.0.5+dfsg2-1. Other package versions are:
avr-libc 1:1.8.0-4
avrdude 6.0.1-1
binutils-avr 2.23.1-2
gcc-avr 1:4.8-2

and then the upload succeeds

**Comment by mdaffin** [comment]
What programmer is cmake set to use?

**Comment by antonpiatek** [comment]
avrisp, I also tried avrispmkii

**Comment by mdaffin** [comment]
If you are using an arduino as the isp programmer then try 'arduinoisp'

**Comment by antonpiatek** [comment]
No its a ftdi shrimp serial adapter

**Comment by queezythegreat** [comment]
Hi, These settings are based on what is already set in the Arduino SDK, all the configuration parameters are directly taken from `${ARDUINO_SDK_PATH}/hardware/arduino/programmers.txt`.

I think this bug is very specific to your hardware, not really related to Arduino-CMake. Closing the ticket for now, reopen it if something new comes up.
